package io.github.sergeyboboshko.cereport.data

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper
import io.github.sergeyboboshko.composeentity_ksp.ceGetDbVersion
import io.github.sergeyboboshko.composeentity_ksp.db.AutoGeneratedOnUpdateSchema
import io.github.sergeyboboshko.composeentity_ksp.db.AutoGeneratedSchema
import io.github.sergeyboboshko.composeentity_ksp.db.DependenciesProvider

class AppDatabase(context: Context) : SQLiteOpenHelper(
    context, "app_database", null, ceGetDbVersion()
) {
    override fun onCreate(db: SQLiteDatabase) {
        // auto CREATE
        AutoGeneratedSchema.tables.forEach { db.execSQL(it) }

//        db.execSQL("""
//            CREATE TABLE accum_reg_my_payments (
//                id INTEGER PRIMARY KEY AUTOINCREMENT,
//                period INTEGER NOT NULL,
//                registratorID INTEGER NOT NULL,
//                stringID INTEGER NOT NULL,
//                registratorType INTEGER NOT NULL,
//                transactionType TEXT NOT NULL,
//                amount REAL NOT NULL,
//                meterR REAL NOT NULL
//)
//        """.trimIndent())
    }

    override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) {
        for (version in (oldVersion + 1)..newVersion) {
            AutoGeneratedOnUpdateSchema.getMigrationStatements(version).forEach { sql ->
                db.execSQL(sql)
            }
        }
        //onCreate(db)
    }
}
